passColor: 05a167
failColor: FF0000
skipColor: a89132
displayTag: true
displayDevice: true
displayAuthor: true
displayFeature: true
displayScenario: true
displayDetailed: true
displayAttached: true
displayExpanded: false

dashboardConfig:
   title: Atheer Test Report  # ✅ Move the title here
   titleColor: null
   dateColor: null
   timeColor: null
   dial:
      featureRanges: 0.60 0.85
      scenarioRanges: 0.60 0.85
      stepRanges: 0.60 0.85
      badColor: null
      averageColor: null
      goodColor: null
   dataBackgroundColor: null